use avabase;

insert into categoria (Nome, Descrizione, idCategoria) values ('T-Shirts Uomo', 'Fai scorta di t-shirt e canotte da uomo online da AVAClothing. Rinnova il tuo guardaroba con t-shirt stampate con tanti motivi trendy e pattern per riflettere la tua personalità. ', 1);
insert into categoria (Nome, Descrizione, idCategoria) values ('Pantaloni Uomo', 'La linea di pantaloni da Uomo include chinos eleganti con tonalità dal kaki al grigio scuro, cargo casual con tasche laterali e joggers da abbinare alle occasioni più sportive. Filtra il colore che fa per te e crea gli abbinamenti che meglio rappresentano il tuo stile. Lasciati ispirare dalla collezione AVAClothing', 2);
insert into categoria (Nome, Descrizione, idCategoria) values ('Scarpe Uomo', 'Completa il tuo outfit con le nostre raffinate scarpe da uomo. Se cerchi dei modelli da indossare tutti i giorni, scopri tanti modelli di sneakers da uomo da infilare o da allacciare, sia minimal che in colori vivaci per adattarsi ai tuoi gusti', 3);
insert into categoria (Nome, Descrizione, idCategoria) values ('Accessori Uomo', 'Crea un look elegante e raffinato grazie alla selezione di accessori da Uomo. Cinture, bretelle, gioielli, basta poco per riuscire a personalizzare ogni outfit con il tuo stile', 4);
insert into categoria (Nome, Descrizione, idCategoria) values ('Felpe Uomo', 'Aggiungi un tocco di calore al tuo guardaroba per tutti i giorni, con la nostra selezione di felpe con o senza cappuccio da uomo. Scopri giacche con cappuccio in colori neutri o felpe stampate con il tuo motivo preferito per il weekend', 5);
insert into categoria (Nome, Descrizione, idCategoria) values ('Camicie Uomo', 'Rendi elegante il tuo look per tutti i giorni con le nostre camicie da uomo. Abbiamo camicie dalla linea slim o regular per adattarsi ai tuoi gusti e alle diverse occasioni, dalle classiche e intramontabili Oxford alle camicie di jeans casual, alle camicie a quadri e in velluto a coste', 6);
insert into categoria (Nome, Descrizione, idCategoria) values ('Top Donna', 'La linea di top da Donna di H&M include modelli per il lavoro e per il fine settimana. Facili da abbinare a una gonna elegante e un jeans casual, la linea include i top corti ideali con un pantalone a palazzo a vita alta, e i body elasticizzati da indossare con una gonna a pieghe. Trova il modello che meglio fa al caso tuo.', 7);
insert into categoria (Nome, Descrizione, idCategoria) values ('Pantaloni Donna e Gonne', 'Classici, moderni, basic e casual. I pantaloni e leggings da Donna di H&M includono modelli adatti ad ogni stile e occasione. Aggiorna il tuo guardaroba con gonne plissettate, a pieghe, volant e maglina', 8);
insert into categoria (Nome, Descrizione, idCategoria) values ('Scarpe Donna', 'Regalati un paio di scarpe nuove: basse e comode o a tacco alto. Stivali, sandali eleganti o sneakers sportive.', 9);
insert into categoria (Nome, Descrizione, idCategoria) values ('Accessori Donna', 'La linea di accessori Donna include cinture scamosciate da annodare a un maxi pull in tinta unita per un look sbarazzino e alla moda.', 10);
insert into categoria (Nome, Descrizione, idCategoria) values ('Felpe Donna', 'Comoda e trendy. La felpa con o senza cappuccio è la scelta più cool per giornate di relax. Scopri tante stampe e modelli alla moda e aggiungi un tocco streetwear al tuo look! ', 11);
insert into categoria (Nome, Descrizione, idCategoria) values ('Camicie Donna', 'Scopri le camicie e le bluse della nuova collezione Donna. Abbina una tunica lunga a un biker di pelle o indossa una camicia di jeans con un pantalone a palazzo in tinta unita', 12);